"""empty message

Revision ID: 129acf5b5601
Revises: e65c502523c0
Create Date: 2021-09-04 06:52:15.494920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129acf5b5601'
down_revision = 'e65c502523c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encomendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('nome_cliente', sa.String(length=32), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('endereco_entrega', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_producao', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('para_encomenda', sa.Boolean(), nullable=True),
    sa.Column('encomenda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encomenda_id'], ['encomendas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entregas', sa.Column('cliente_whatsapp', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entregas', 'cliente_whatsapp')
    op.drop_table('producao')
    op.drop_table('encomendas')
    # ### end Alembic commands ###
