"""empty message

Revision ID: 76cbab82c903
Revises: d9c03cc35f65
Create Date: 2021-09-02 06:06:51.639993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cbab82c903'
down_revision = 'd9c03cc35f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos_venda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos_venda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pontos_venda_pkey')
    )
    # ### end Alembic commands ###
