"""Primeira migração

Revision ID: d9c03cc35f65
Revises: 
Create Date: 2021-09-02 05:51:52.207161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c03cc35f65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_ponto_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos_de_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=True),
    sa.Column('local', sa.String(length=64), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('tipo_ponto_venda_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_ponto_venda_id'], ['tipo_ponto_venda.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('entregas', sa.Column('destino', sa.String(length=64), nullable=True))
    op.add_column('entregas', sa.Column('cliente_nome', sa.String(length=32), nullable=True))
    op.add_column('entregas', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.add_column('entregas', sa.Column('entregador_id', sa.Integer(), nullable=True))
    op.add_column('entregas', sa.Column('unidade_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_unidades_id', 'entregas', 'unidades', ['unidade_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_usuarios_id', 'entregas', 'usuarios', ['entregador_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_pedidos_id', 'entregas', 'pedidos', ['pedido_id'], ['id'], use_alter=True)
    op.drop_constraint('pedidos_ponto_de_venda_id_fkey', 'pedidos', type_='foreignkey')
    op.create_foreign_key('fk_pontos_de_venda_id', 'pedidos', 'pontos_de_venda', ['ponto_de_venda_id'], ['id'], use_alter=True)
    op.add_column('pedidos_itens', sa.Column('preco_data', sa.Float(), nullable=True))
    op.add_column('pedidos_itens', sa.Column('quantidade', sa.Integer(), nullable=True))
    op.add_column('unidades', sa.Column('nome', sa.String(length=32), nullable=True))
    op.add_column('unidades', sa.Column('cidade', sa.String(length=32), nullable=True))
    op.add_column('unidades', sa.Column('bairro', sa.String(length=32), nullable=True))
    op.add_column('unidades', sa.Column('endereco', sa.String(length=32), nullable=True))
    op.add_column('unidades', sa.Column('data_cadastro', sa.Date(), nullable=True))
    op.add_column('unidades', sa.Column('gerente_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_usuarios_id', 'unidades', 'usuarios', ['gerente_id'], ['id'], use_alter=True)
    op.add_column('usuarios', sa.Column('unidade_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_unidades_id', 'usuarios', 'unidades', ['unidade_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unidades_id', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'unidade_id')
    op.drop_constraint('fk_usuarios_id', 'unidades', type_='foreignkey')
    op.drop_column('unidades', 'gerente_id')
    op.drop_column('unidades', 'data_cadastro')
    op.drop_column('unidades', 'endereco')
    op.drop_column('unidades', 'bairro')
    op.drop_column('unidades', 'cidade')
    op.drop_column('unidades', 'nome')
    op.drop_column('pedidos_itens', 'quantidade')
    op.drop_column('pedidos_itens', 'preco_data')
    op.drop_constraint('fk_pontos_de_venda_id', 'pedidos', type_='foreignkey')
    op.create_foreign_key('pedidos_ponto_de_venda_id_fkey', 'pedidos', 'pontos_venda', ['ponto_de_venda_id'], ['id'])
    op.drop_constraint('fk_pedidos_id', 'entregas', type_='foreignkey')
    op.drop_constraint('fk_usuarios_id', 'entregas', type_='foreignkey')
    op.drop_constraint('fk_unidades_id', 'entregas', type_='foreignkey')
    op.drop_column('entregas', 'unidade_id')
    op.drop_column('entregas', 'entregador_id')
    op.drop_column('entregas', 'pedido_id')
    op.drop_column('entregas', 'cliente_nome')
    op.drop_column('entregas', 'destino')
    op.create_table('pontos_venda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pontos_venda_pkey')
    )
    op.drop_table('pontos_de_venda')
    op.drop_table('equipamentos')
    op.drop_table('tipo_ponto_venda')
    # ### end Alembic commands ###
