"""empty message

Revision ID: e65c502523c0
Revises: 8d7aeb6ba8cf
Create Date: 2021-09-04 05:31:05.121784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65c502523c0'
down_revision = '8d7aeb6ba8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregas', sa.Column('data_registro', sa.DateTime(), nullable=True))
    op.add_column('entregas', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_unidades_id', 'entregas', 'unidades', ['unidade_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_usuarios_id', 'entregas', 'usuarios', ['entregador_id'], ['id'], use_alter=True)
    op.drop_column('entregas', 'concluida')
    op.create_foreign_key('fk_usuarios_id', 'unidades', 'usuarios', ['gerente_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_id', 'unidades', type_='foreignkey')
    op.add_column('entregas', sa.Column('concluida', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_usuarios_id', 'entregas', type_='foreignkey')
    op.drop_constraint('fk_unidades_id', 'entregas', type_='foreignkey')
    op.drop_column('entregas', 'status')
    op.drop_column('entregas', 'data_registro')
    # ### end Alembic commands ###
