"""empty message

Revision ID: fafe56317364
Revises: 129acf5b5601
Create Date: 2021-09-06 06:02:54.082164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafe56317364'
down_revision = '129acf5b5601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=64), nullable=True),
    sa.Column('conteudo', sa.String(length=255), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('data_aberta', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('ponto_venda_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_ponto_venda_id', 'usuarios', 'pontos_de_venda', ['ponto_venda_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ponto_venda_id', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'ponto_venda_id')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
